import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { CartClient } from "./(shared-default-layout)/_components";
import { dir } from "i18next";
import { languages } from "../i18n/settings";
import { LanguageClient } from "../i18n/LanguageClient";
import { CssBaseline, ThemeProvider } from "@mui/material";
import theme from "@/styles/theme";

const inter = Inter({ subsets: ["latin"] });

export const generateStaticParams = () =>
  languages.map((language) => ({ language }));

export const metadata: Metadata = {
  title: "Home of Pianists",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { language },
}: Readonly<{
  children: React.ReactNode;
  params: { language: string };
}>) {
  return (
    <html lang={language} dir={dir(language)}>
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <LanguageClient language={language}>
            <ThemeProvider theme={theme}>
              <CssBaseline />
              <CartClient>{children}</CartClient>
            </ThemeProvider>
          </LanguageClient>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
