import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeClient from "@/styles/ThemeClient";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { CartClient } from "./(shared-default-layout)/_components";
import { dir } from "i18next";
import { languages } from "../i18n/settings";
import { I18nClient } from "./(shared-default-layout)/_components/I18nClient";

const inter = Inter({ subsets: ["latin"] });

export const generateStaticParams = () =>
  languages.map((language) => ({ language }));

export const metadata: Metadata = {
  title: "Home of Pianists",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { language },
}: Readonly<{
  children: React.ReactNode;
  params: { language: string };
}>) {
  return (
    <html lang={language} dir={dir(language)}>
      <body className={inter.className} id="root">
        <AppRouterCacheProvider>
          <I18nClient language={language}>
            <CartClient>
              <ThemeClient>{children}</ThemeClient>
            </CartClient>
          </I18nClient>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
