import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeClient from "@/styles/ThemeClient";
import { Divider, Stack } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { CartProvider } from "react-use-cart";
import { auth } from "@/auth";
import { Header, Footer } from "./components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home of Pianists",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <CartProvider>
            <ThemeClient>
              <Stack>
                <Header session={session}/>
                {children}
                <Divider variant="fullWidth" className="pt-10" />
                <Footer />
              </Stack>
            </ThemeClient>
          </CartProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
