import { Course, CourseType } from '@prisma/client';

export const courses: Course[] = [
  {
    id: "1",
    title: "Beginner Piano Basics",
    description: "Learn the fundamentals of piano playing.",
    price: 50,
    createdAt: new Date(),
    updatedAt: new Date(),
    teacherId: "teacher1",
    courseType: CourseType.online,
    address: "Online",
    skillLevel: "Beginner",
    startDate: new Date(),
    durationInWeeks: 8,
    maxStudents: 120,
    latitude: 0,
    longitude: 0,
  },
  {
    id: "2",
    title: "Intermediate Classical Piano",
    description: "Dive deeper into classical piano techniques.",
    price: 75,
    createdAt: new Date(),
    updatedAt: new Date(),
    teacherId: "teacher2",
    courseType: CourseType.offline,
    address: "New York, NY",
    skillLevel: "Intermediate",
    startDate: new Date(),
    durationInWeeks: 12,
    maxStudents: 80,
    latitude: 40.7128,
    longitude: -74.006,
  },
  {
    id: "3",
    title: "Jazz Piano Improvisation",
    description: "Master the art of jazz improvisation on piano.",
    price: 100,
    createdAt: new Date(),
    updatedAt: new Date(),
    teacherId: "teacher3",
    courseType: CourseType.online,
    address: "Online",
    skillLevel: "Advanced",
    startDate: new Date(),
    durationInWeeks: 10,
    maxStudents: 60,
    latitude: 0,
    longitude: 0,
  },
  {
    id: "4",
    title: "Piano Theory Fundamentals",
    description: "Understand the theoretical foundations of piano music.",
    price: 40,
    createdAt: new Date(),
    updatedAt: new Date(),
    teacherId: "teacher4",
    courseType: CourseType.online,
    address: "Online",
    skillLevel: "Beginner",
    startDate: new Date(),
    durationInWeeks: 6,
    maxStudents: 150,
    latitude: 0,
    longitude: 0,
  },
  {
    id: "5",
    title: "Advanced Composition for Piano",
    description: "Learn advanced techniques for composing piano music.",
    price: 120,
    createdAt: new Date(),
    updatedAt: new Date(),
    teacherId: "teacher5",
    courseType: CourseType.offline,
    address: "Los Angeles, CA",
    skillLevel: "Advanced",
    startDate: new Date(),
    durationInWeeks: 16,
    maxStudents: 30,
    latitude: 34.0522,
    longitude: -118.2437,
  },
  {
    id: "6",
    title: "Pop Piano Techniques",
    description: "Master popular piano techniques for contemporary music.",
    price: 65,
    createdAt: new Date(),
    updatedAt: new Date(),
    teacherId: "teacher6",
    courseType: CourseType.online,
    address: "Online",
    skillLevel: "Intermediate",
    startDate: new Date(),
    durationInWeeks: 8,
    maxStudents: 100,
    latitude: 0,
    longitude: 0,
  },
  {
    id: "7",
    title: "Local Piano Workshop",
    description: "Hands-on piano workshop for beginners in Chicago.",
    price: 80,
    createdAt: new Date(),
    updatedAt: new Date(),
    teacherId: "teacher7",
    courseType: CourseType.offline,
    address: "Chicago, IL",
    skillLevel: "Beginner",
    startDate: new Date(),
    durationInWeeks: 4,
    maxStudents: 15,
    latitude: 41.8781,
    longitude: -87.6298,
  },
  {
    id: "8",
    title: "Classical Piano Masterclass",
    description: "Advanced masterclass for classical piano enthusiasts.",
    price: 150,
    createdAt: new Date(),
    updatedAt: new Date(),
    teacherId: "teacher8",
    courseType: CourseType.offline,
    address: "Boston, MA",
    skillLevel: "Advanced",
    startDate: new Date(),
    durationInWeeks: 2,
    maxStudents: 10,
    latitude: 42.3601,
    longitude: -71.0589,
  },
  {
    id: "9",
    title: "Vietnamese Traditional Piano",
    description: "Explore traditional Vietnamese music on piano.",
    price: 70,
    createdAt: new Date(),
    updatedAt: new Date(),
    teacherId: "teacher9",
    courseType: CourseType.offline,
    address: "Hanoi, Vietnam",
    skillLevel: "Intermediate",
    startDate: new Date(),
    durationInWeeks: 10,
    maxStudents: 20,
    latitude: 21.0278,
    longitude: 105.8342,
  },
  {
    id: "10",
    title: "Piano for Kids",
    description: "Fun and engaging piano lessons for children.",
    price: 55,
    createdAt: new Date(),
    updatedAt: new Date(),
    teacherId: "teacher10",
    courseType: CourseType.offline,
    address: "Hanoi, Vietnam",
    skillLevel: "Beginner",
    startDate: new Date(),
    durationInWeeks: 12,
    maxStudents: 15,
    latitude: 21.0360,
    longitude: 105.8340,
  },
  {
    id: "11",
    title: "Advanced Piano Techniques",
    description: "Master advanced piano techniques and performance skills.",
    price: 100,
    createdAt: new Date(),
    updatedAt: new Date(),
    teacherId: "teacher11",
    courseType: CourseType.offline,
    address: "Hanoi, Vietnam",
    skillLevel: "Advanced",
    startDate: new Date(),
    durationInWeeks: 14,
    maxStudents: 10,
    latitude: 21.0259,
    longitude: 105.8605,
  },
];